services:
  backend:
    build: ./backend
    image: backend:latest
    ports:
      - "8000:8000"
    networks:
      - internal_network
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True

  frontend:
    image: frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - internal_network
    volumes:
      - /app/node_modules
      - ./frontend:/app

networks:
  internal_network: