services:
  backend:
    build: .
    ports:
      - "5000:5000"
    networks:
      - internal_network

  frontend:
    image: frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - internal_network
    volumes:
      - /app/node_modules
      - ./frontend:/app

networks:
  internal_network:
