# Generated by Django 5.1.4 on 2025-03-17 00:23

import django.db.models.deletion
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionOffice',
            fields=[
                ('tu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fb_sb_wf', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=320)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('email', models.EmailField(max_length=320)),
                ('matr_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('semester_address', models.CharField(max_length=255)),
                ('list_password', models.CharField(max_length=255)),
                ('fb_sb_label', models.CharField(max_length=255)),
                ('semester', models.CharField(choices=[('WS', 'Winter semester'), ('SS', 'Summer semester')], max_length=2)),
                ('semester_year', models.CharField(max_length=10)),
                ('committee', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('matr_number', 'committee', 'semester_year')},
            },
        ),
        migrations.CreateModel(
            name='NominationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('WS', 'Winter semester'), ('SS', 'Summer semester')], max_length=2)),
                ('semester_year', models.CharField(max_length=10)),
                ('list_password', models.CharField(max_length=255)),
                ('number_of_candidates', models.IntegerField()),
                ('date', models.DateField()),
                ('committee_fb_sb_wf', models.TextField(blank=True, null=True)),
                ('election_office', models.ForeignKey(default=forms.models.ElectionOffice.get_default_election_office, on_delete=django.db.models.deletion.CASCADE, to='forms.electionoffice')),
                ('trusted_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.trustedperson')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('fb_sb', models.CharField(max_length=255)),
                ('nomination_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.nominationlist')),
            ],
        ),
    ]
