# Generated by Django 5.1.4 on 2025-01-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionOffice',
            fields=[
                ('tu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fb_sb', models.CharField(max_length=255)),
                ('address_zip', models.CharField(max_length=10)),
                ('address_city', models.CharField(max_length=100)),
                ('address_street', models.CharField(max_length=100)),
                ('address_additional', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=320)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NominationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('WS', 'Winter semester'), ('SS', 'Summer semester')], max_length=2)),
                ('semester_year', models.CharField(max_length=10)),
                ('committee', models.CharField(max_length=255)),
                ('fb_sb_wf', models.CharField(blank=True, max_length=255, null=True)),
                ('list_password', models.CharField(max_length=255)),
                ('number_of_candidates', models.IntegerField()),
                ('date', models.DateField()),
                ('consideration', models.CharField(choices=[('1', 'Considered'), ('0', 'Not considered')], max_length=1)),
                ('justification', models.TextField(blank=True, null=True)),
                ('election_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.electionoffice')),
                ('trusted_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.trustedperson')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('fb_sb', models.CharField(max_length=255)),
                ('matr_number', models.IntegerField()),
                ('nomination_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.nominationlist')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('email', models.EmailField(max_length=320)),
                ('matr_number', models.IntegerField()),
                ('address_zip', models.CharField(max_length=10)),
                ('address_city', models.CharField(max_length=100)),
                ('address_street', models.CharField(max_length=100)),
                ('address_house_number', models.CharField(max_length=20)),
                ('address_additional', models.CharField(blank=True, max_length=100, null=True)),
                ('semester_address_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('semester_address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('semester_address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('semester_address_house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('semester_address_additional', models.CharField(blank=True, max_length=100, null=True)),
                ('list_password', models.CharField(max_length=255)),
                ('fb', models.CharField(blank=True, max_length=255, null=True)),
                ('sb_label', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(choices=[('WS', 'Winter semester'), ('SS', 'Summer semester')], max_length=2)),
                ('semester_year', models.CharField(max_length=10)),
                ('committee', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.candidate')),
            ],
            options={
                'unique_together': {('candidate', 'committee', 'semester_year')},
            },
        ),
    ]
