# Generated by Django 5.1.4 on 2025-01-26 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together={('matr_number', 'committee', 'semester_year')},
        ),
        migrations.AlterField(
            model_name='nominationlist',
            name='election_office',
            field=models.ForeignKey(default='12345678', on_delete=django.db.models.deletion.CASCADE, to='forms.electionoffice'),
        ),
        migrations.RemoveField(
            model_name='consent',
            name='candidate',
        ),
    ]
