# Generated by Django 5.1.4 on 2025-01-26 22:43

import django.db.models.deletion
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_consent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationlist',
            name='election_office',
            field=models.ForeignKey(default=forms.models.ElectionOffice.get_default_election_office, on_delete=django.db.models.deletion.CASCADE, to='forms.electionoffice'),
        ),
    ]
